spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mooc_supermarket?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

axios:
  defaults:
    withCredentials: true



#logging:
#  path: ./log/tomcat
#  file: ./log/tomcat/sell.log
#  level: debug
#  pattern:
#    console: "%d -%msg %n " #日期，日志信息， 换行


